### ISSUE TITLE
config.php is not working properly in the server.

### ISSUE THREAD

**Issue by Sagar-03** [kirthik-d/Newsportal#10]
config.php is not opening properly showing the issue that error that it has the issue of fatal error in the code

**Comment by kirthikprofile** [comment]
Actually this is the file for configuration of database connection with this application, so make sure you have created database in the sql server before running, 
you can use phpmyadmin page to create database and import the newsportal.sql file given in this project to execute queries. So. Please use xampp server and start the sql server.
