### ISSUE TITLE
Regarding adding security features for having detailed policies 

### ISSUE THREAD

**Issue by Vaibhav2154** [kirthik-d/Newsportal#6]
Seeking to elevate your news portal website with a pivotal feature? I propose integrating a Privacy Policy page into your platform, guaranteeing adherence to legal requirements and reinforcing user confidence. My input will strengthen your website's credibility and safeguard user information, aligning with modern norms of online transparency and protection. By adopting an open-source strategy, this inclusion will be tailored to your website's unique requirements and effortlessly manageable for subsequent modifications. Let's work together to prioritize user privacy and enhance your platform's reputation with this indispensable upgrade.

**Comment by anuragverma108** [comment]
@Vaibhav2154 Think of something of your own. Don't copy me brother. I have already raised similar issue before you.

**Comment by Vaibhav2154** [comment]
I've already worked out and had a pull request before you. Apparantly I don't think you're the only one who can do that.

**Comment by anuragverma108** [comment]
This is not a code of conduct. I think you are a newbie in this Opensource world. Since I had raised the issue first so the Maintainer will assign me first. You have just duplicated my issue. And maintainer haven't assigned it to you yet. Fist learn how to raise an issue and get it assigned then come to contribute. Reaching out on LinkedIn first doesn't matter at all. Who creates the issue first on GitHub repo that matters, you don't even know this.

**Comment by Vaibhav2154** [comment]
> @Vaibhav2154 This is not a code of conduct. I think you are a newbie in this Opensource world. Since I had raised the issue first so the Maintainer will assign me first. You have just duplicated my issue. And maintainer haven't assigned it to you yet. Fist learn how to raise an issue and get it assigned then come to contribute. Reaching out on LinkedIn first doesn't matter at all. Who creates the issue first on GitHub repo that matters, you don't even know this.

All the best do well!

**Comment by kirthik-d** [comment]
@anuragverma108 While it's true that the order of issue creation can sometimes cause assignment priority, it's not the only factor we consider. Our goal is to ensure that all contributors feel valued and supported in their contributions. 
Thank you both of you for raising similar issues and showed interest. I look forward to see you both work together on the issues. Thanks:)
